#!/bin/bash
repo(){
  # create a repo to host a new project on GitHub
  git init
  git add .
  git commit -m "And so, it begins."
  hub create -p
  # (creates a new GitHub repository with the name of the current directory)
  git push -u origin HEAD

}
repo
