#!/bin/bash

   for testInput in ./test/*.in; do
      name=${testInput%.in}
      printf "$name\n"
      /home/kmammen/357/Project2/swc -l -c $testInput>$name.expect 2>$name.errm
      ./a.out  <$testInput> $name.actual 2>$name.err
      echo "Exit status/return code: " $?
      diff -q $name.actual $name.expect
      diff -q $name.err $name.errm
   done
