#!/bin/bash

complexity -t0 -s1 -H *.c | awk '{print $1}'>> c.log
echo
complexity -t0 -s1 -H *.c | awk 'BEGIN { printf "%10s %27s\n", "Complexity:", "Functions:"
                                         printf "%10s %27s\n", "-----------", "----------" }
                                        {printf ("%5s%20s\t%s\n", $1, $4, $5)} '
sort -nr -o c.log c.log

filename='c.log'
array=( $(<"$filename") )                 #Save the input file in array
len=${#array[@]}                          #Total functions number
sum=$(IFS=+; echo "$((${array[*]}))")     #Total complexity
Average=$(awk "BEGIN {print $sum/$len}")  #Calculate the average
lineNumber=$(echo "scale=0;$len*0.25" |bc | awk '{print int($1+0.5)}')

top=0;counter=0; 
#------calculate Top Max-------#
for line in "${array[@]}"
do
   ((counter++))
   top=$((top+line))
   
   if [ $counter == $lineNumber ]; then
      break
   fi
done

Ratio=$(awk "BEGIN {print $top/$sum}")

echo 
echo "-----------------------------------"
echo "   Total Complexity:|  ${sum}       "
echo "-----------------------------------"
echo " Maximum Complexity:|  ${array[0]}       "
echo "------------------------------------"
echo " Average Complexity:|  ${Average}   "
echo "------------------------------------"
echo "              Ratio:|  ${Ratio}   "
echo "------------------------------------"
echo

rm -rf c.log