#!/bin/bash

szip(){
   [ -z $1 ] && echo "Exercise number: null" && exit
   
   if [[ -f *.h ]]; then
      zip Project$1.zip *.h *.c
   else
      zip Project$1.zip  *.c
   fi

   handin kmammen-grader Project$1 Project$1.zip

}
szip $1
