#!/bin/bash

szip(){
   [ -z $1 ] && echo "Exercise number: null" && exit
   
   if [ -f *.h ]; then
      zip Exercise$1.zip *.h *.c
   else
      zip Exercise$1.zip  *.c
   fi

   handin kmammen-grader Exercise$1-Section7 Exercise$1.zip

}
szip $1